package mods.roborave.edm;
import java.util.Arrays;

import com.google.common.eventbus.Subscribe;

import net.minecraft.command.ICommandSender;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.ChatComponentTranslation;
import mods.roborave.command.EDMCommand;
import mods.roborave.edm.Handler.EDMEventHandler;
import mods.roborave.edm.chat.ChatMessageHandler;
import mods.roborave.edm.helper.LocalizationHandler;
import mods.roborave.edm.helper.LogHandler;
import mods.roborave.edm.helper.Version;
import mods.roborave.edm.init.Blocks;
import mods.roborave.edm.init.Items;
import mods.roborave.edm.lib.Strings;
import mods.roborave.event.EDMEvent;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartedEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import cpw.mods.fml.server.FMLServerHandler;

@Mod(modid = Strings.MODID, name = Strings.name, version = Strings.version,canBeDeactivated=true)

public class EDM extends DummyModContainer{
	
	public static LogHandler log;
	
	@Instance(Strings.MODID)
	public static EDM Instance;
	
	public EntityPlayer player;
	public ICommandSender sender;
	public Strings lib;
	/**
	 * Loads before
	 * @param PreEvent
	 */
	@EventHandler
	public static void PreLoad(FMLPreInitializationEvent PreEvent)
	{
		EDMEventHandler.init();
		ModMetadata meta = PreEvent.getModMetadata();
		meta.autogenerated = false;
		meta.credits = "(C) Roborave, 2013-2014";
		meta.authorList = Arrays.asList("Roborave");
		meta.name = Strings.name;
		meta.version = Strings.version;
		meta.description = "";
		
		LocalizationHandler.init();
		Blocks.init();
		Items.init();
		Blocks.TestBlocks();
		
    }
	
	/**
	 * Loads during
	 * @param event
	 */
	@EventHandler
	public static void load(FMLInitializationEvent event)
	{
		
	}
	
	/**
	 * Loads after
	 * @param PostEvent
	 */
	@EventHandler
	public static void PostLoad(FMLPostInitializationEvent PostEvent)
	{
		
	}
	@EventHandler
	@Subscribe
	 public void serverStarting(FMLServerStartingEvent evt)
	 {
		 evt.registerServerCommand(new EDMCommand(evt.getServer()));
	 }
	
}
